# DOCKER-COMPOSE.YML
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
